/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root"
import { Route as PosRouteImport } from "./app/pos"
import { Route as IndexRouteImport } from "./app/index"
import { Route as DataTableClientIndexRouteImport } from "./app/data-table-client/index"

const PosRoute = PosRouteImport.update({
  id: "/pos",
  path: "/pos",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DataTableClientIndexRoute = DataTableClientIndexRouteImport.update({
  id: "/data-table-client/",
  path: "/data-table-client/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/pos": typeof PosRoute
  "/data-table-client/": typeof DataTableClientIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/pos": typeof PosRoute
  "/data-table-client": typeof DataTableClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/pos": typeof PosRoute
  "/data-table-client/": typeof DataTableClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/pos" | "/data-table-client/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/pos" | "/data-table-client"
  id: "__root__" | "/" | "/pos" | "/data-table-client/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PosRoute: typeof PosRoute
  DataTableClientIndexRoute: typeof DataTableClientIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/pos": {
      id: "/pos"
      path: "/pos"
      fullPath: "/pos"
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/data-table-client/": {
      id: "/data-table-client/"
      path: "/data-table-client"
      fullPath: "/data-table-client/"
      preLoaderRoute: typeof DataTableClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PosRoute: PosRoute,
  DataTableClientIndexRoute: DataTableClientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
